@accountId = b27d2eb4-9210-4b1a-ae06-a3d944e59d0a

### create account
POST http://localhost:8080/api/accounts
Content-Type: application/json

{
  "ownerName": "Tony Stark",
  "ownerUserId": "ecd03205-17f1-4d2e-8708-552f0bd21b6f",
  "creatorId": "db1c3cc6-aacc-4bc7-b198-58a84109fdf5",
  "currency": "EUR"
}
###

### Deposit
POST http://localhost:8080/api/accounts/{{accountId}}/deposit
Content-Type: application/json

{
  "amount": 100.00,
  "currency": "EUR"
}
###

### Withdraw
POST http://localhost:8080/api/accounts/{{accountId}}/withdraw
Content-Type: application/json

{
    "amount": 20.00,
    "currency": "EUR"
}

### ballance
GET http://localhost:8080/api/accounts/{{accountId}}/balance
Content-Type: application/json

### close account
POST http://localhost:8080/api/accounts/{{accountId}}/close
Content-Type: application/json